export const MEMBER_TABLE_COLUMNS = [
  { id: 'profile', label: '이름/자기소개', width: 'w-[220px] min-w-[220px]' },
  { id: 'role', label: '역할', width: 'w-[118px]' },
  { id: 'position', label: '포지션', width: 'w-[172px]' },
  { id: 'department', label: '학과', width: 'w-[190px]' },
  { id: 'studentId', label: '학번', width: 'w-[138px]' },
  { id: 'statsStartGap', label: '', width: 'w-6 min-w-6 !px-0' },
  { id: 'attendance', label: '출석', width: 'w-16 min-w-16 !px-100', align: 'text-center' },
  { id: 'absence', label: '결석', width: 'w-16 min-w-16 !px-100', align: 'text-center' },
  { id: 'penalty', label: '페널티', width: 'w-16 min-w-16 !px-100', align: 'text-center' },
  { id: 'warning', label: '경고', width: 'w-16 min-w-16 !px-100', align: 'text-center' },
  { id: 'statsEndGap', label: '', width: 'w-6 min-w-6 !px-0' },
  { id: 'phone', label: '전화번호', width: 'w-[146px]' },
  { id: 'cardinal', label: '기수', width: 'w-[182px]' },
] as const;
