export { HeroSection } from './HeroSection';
export { PhilosophySection } from './PhilosophySection';
export { FeatureIntroSection } from './FeatureIntroSection';
export { ServiceSection } from './ServiceSection';
export type { Feature } from './ServiceSection';
export { SetupGuideSection } from './SetupGuideSection';
export { TestimonialSection } from './TestimonialSection';
export { ClubTypesSection } from './ClubTypesSection';
export { CTASection } from './CTASection';
export { LandingFooter } from './LandingFooter';
