name: Preview

on:
  pull_request:
    branches: ['develop']

jobs:
  vercel-preview:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      deployments: write
      id-token: write
      issues: write
      pull-requests: write

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Install pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        with:
          version: 10.28.0

      - name: Install Vercel CLI
        run: pnpm add -g vercel@latest

      - name: Get Vercel Environment Variables

        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts

        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel

        id: deploy

        run: |

          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > vercel-output.txt

          echo "preview_url=$(cat vercel-output.txt)" >> $GITHUB_OUTPUT

      - name: Comment PR with Preview URL

        uses: thollander/actions-comment-pull-request@fabd468d3a1a0b97feee5f6b9e499eab0dd903f6 # v2

        with:
          message: |

            구현한 기능 Preview: ${{ steps.deploy.outputs.preview_url }}
